# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internvla_stream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16internvla_stream.proto\x12\x10internvla.stream\"\'\n\x0bInstruction\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\"]\n\x05\x46rame\x12\x12\n\nimage_jpeg\x18\x01 \x01(\x0c\x12\x11\n\tdepth_png\x18\x02 \x01(\x0c\x12\r\n\x05reset\x18\x03 \x01(\x08\x12\x0b\n\x03seq\x18\x04 \x01(\x04\x12\x11\n\tclient_id\x18\x05 \x01(\t\"+\n\tHeartbeat\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\xac\x01\n\rClientMessage\x12(\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x17.internvla.stream.FrameH\x00\x12\x34\n\x0binstruction\x18\x02 \x01(\x0b\x32\x1d.internvla.stream.InstructionH\x00\x12\x30\n\theartbeat\x18\x03 \x01(\x0b\x32\x1b.internvla.stream.HeartbeatH\x00\x42\t\n\x07payload\"|\n\x06\x41\x63tion\x12\x17\n\x0f\x64iscrete_action\x18\x01 \x03(\x05\x12\x12\n\ntrajectory\x18\x02 \x03(\x02\x12\x12\n\npixel_goal\x18\x03 \x03(\x02\x12\x0b\n\x03log\x18\x04 \x01(\t\x12\x17\n\x0foverlay_png_b64\x18\x05 \x01(\t\x12\x0b\n\x03seq\x18\x06 \x01(\x04\"x\n\rServerMessage\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x18.internvla.stream.ActionH\x00\x12\x30\n\theartbeat\x18\x02 \x01(\x0b\x32\x1b.internvla.stream.HeartbeatH\x00\x42\t\n\x07payload2a\n\x0fInternVLAStream\x12N\n\x06Stream\x12\x1f.internvla.stream.ClientMessage\x1a\x1f.internvla.stream.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internvla_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSTRUCTION']._serialized_start=44
  _globals['_INSTRUCTION']._serialized_end=83
  _globals['_FRAME']._serialized_start=85
  _globals['_FRAME']._serialized_end=178
  _globals['_HEARTBEAT']._serialized_start=180
  _globals['_HEARTBEAT']._serialized_end=223
  _globals['_CLIENTMESSAGE']._serialized_start=226
  _globals['_CLIENTMESSAGE']._serialized_end=398
  _globals['_ACTION']._serialized_start=400
  _globals['_ACTION']._serialized_end=524
  _globals['_SERVERMESSAGE']._serialized_start=526
  _globals['_SERVERMESSAGE']._serialized_end=646
  _globals['_INTERNVLASTREAM']._serialized_start=648
  _globals['_INTERNVLASTREAM']._serialized_end=745
# @@protoc_insertion_point(module_scope)
