# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import internvla_stream_pb2 as internvla__stream__pb2


class InternVLAStreamStub(object):
    """Bidirectional streaming for InternVLA inference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/internvla.stream.InternVLAStream/Stream',
                request_serializer=internvla__stream__pb2.ClientMessage.SerializeToString,
                response_deserializer=internvla__stream__pb2.ServerMessage.FromString,
                )


class InternVLAStreamServicer(object):
    """Bidirectional streaming for InternVLA inference.
    """

    def Stream(self, request_iterator, context):
        """Client opens one stream and sends frames/instructions/heartbeats.
        Server responds with actions/heartbeats on the same stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternVLAStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=internvla__stream__pb2.ClientMessage.FromString,
                    response_serializer=internvla__stream__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internvla.stream.InternVLAStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InternVLAStream(object):
    """Bidirectional streaming for InternVLA inference.
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/internvla.stream.InternVLAStream/Stream',
            internvla__stream__pb2.ClientMessage.SerializeToString,
            internvla__stream__pb2.ServerMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
